version: 1
input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metrics_path: "models/metrics.json"
split_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "CatBoostClassifier"
feature_params:
  cat_features:
    - "ca"
    - "cp"
    - "exang"
    - "fbs"
    - "restecg"
    - "sex"
    - "slope"
  num_features:
    - "age"
    - "chol"
    - "oldpeak"
    - "thalach"
    - "trestbps"
  drop_features: []
  target_col: "target"