version: 1
input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metrics_path: "models/metrics.json"
defaults:
  - split_params: "20_42"
  - train_params: classifier
  - feature_params: all_features
