apiVersion: v1
kind: Pod
metadata:
  name: online-inference
spec:
  containers:
    - name: ml-service
      image: ruk0sh/online_inference:v1
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
