apiVersion: v1
kind: Pod
metadata:
  name: online-inference
spec:
  containers:
    - name: ml-service
      image: ruk0sh/online_inference:v2
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "128 Mi"
          cpu: "250m"
        limits:
          memory: "256 Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10