feature_params:
  cat_features:
    - "ca"
    - "cp"
    - "exang"
    - "fbs"
    - "restecg"
    - "sex"
    - "slope"
    - "thal"
  num_features:
    - "age"
    - "chol"
    - "oldpeak"
    - "thalach"
    - "trestbps"
  drop_features: []
  target_col: "target"